name: Test Npm publish and change log
on:
  push:
    branches:
      - main # master 分支有 push 行为时就触发这个 action

jobs:
  publish:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set timezone to Asia/Shanghai
        uses: szenius/set-timezone@v1.0
        with:
          # 设置执行环境的时区为 Linux 上海时区
          timezoneLinux: "Asia/Shanghai"

      - name: Echo current time
        run: timedatectl

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Install pnpm
        run: |
          npm install -g pnpm
          # pnpm config set store-dir $(pwd)/.pnpm-store
          # pnpm config set recursive-optional true

      - name: Install Dependence
        run: pnpm i

      - name: Build dist
        run: pnpm run build

      - name: Start publish
        run: npm publish --dry-run # 如果发布之前需要构建，可添加prepublishOnly的生命周期脚本
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} # 上面在Github Secrets中设置的密钥
