name: Test Npm publish and change log
on:
  push:
    branches:
      - main # master 分支有 push 行为时就触发这个 action

jobs:
  publish:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set timezone to Asia/Shanghai
        uses: szenius/set-timezone@v1.0
        with:
          # 设置执行环境的时区为 Linux 上海时区
          timezoneLinux: "Asia/Shanghai"

      - name: Echo current time
        run: timedatectl

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Install pnpm
        run: |
          npm install -g pnpm
          # pnpm config set store-dir $(pwd)/.pnpm-store
          # pnpm config set recursive-optional true

      - name: Install Dependence
        run: pnpm i

      - name: Build dist
        run: pnpm run build

      - name: Start publish
        run: npm publish --dry-run # 如果发布之前需要构建，可添加prepublishOnly的生命周期脚本
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} # 上面在Github Secrets中设置的密钥

      - name: Set Git user and email
        run: |
          git config --local user.name ${{vars.NAME}}
          git config --local user.email ${{vars.EMAIL}}

      - name: Update Version
        run: |
          # 更新版本号并获取新版本号
          VERSION=$(npm version patch --no-git-tag-version --silent)
          # 将新版本号输出到环境变量
          echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Commit and push version bump
        run: |
          git add package.json
          git commit -m "Bump version to ${{ env.NEW_VERSION }}"
          git tag -a "${{ env.NEW_VERSION }}" -m "Release ${{ env.NEW_VERSION }}"
          git push origin main --tags

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: "${{ env.NEW_VERSION }}"
          release_name: "Release ${{ env.NEW_VERSION }}"
          body: "Check the changelog for details."
          draft: false
          prerelease: false
